[package]
name = "netify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
yew-router = "0.16.0"
yewdux-functional = "0.1.0"
yewdux = "0.7.0"
serde = { version = "1.0.114" }

rand = "0.8.5"
wasm-bindgen = "0.2.80"
getrandom = { version = "0.2", features = ["js"] }
web-sys = { version = "0.3.56", features = ["Request", "Window"] }
gloo = "0.6.1"
