[package]
name = "yewapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
rand = "0.8.5"
wasm-bindgen = "0.2.80"
getrandom = { version = "0.2", features = ["js"] }
web-sys = { version = "0.3.56", features = ["Request", "Window"] }
